### ISSUE TITLE
what if the image in the same url is changes?

### ISSUE THREAD

**Issue by anudeep94** [konoma/matisse#3]
what if the image changes, url remains the same as before, i have noted that its not updating.

**Comment by frenetisch-applaudierend** [comment]
Hi Anudeep

You are correct, the image is cached locally and only once retrieved from the server. There is currently no functionality to remove an image from the cache again. 

As a workaround you could either provide your own caching classes and add the purging mechanism there (unfortunately you probably cannot reuse the existing caches; fortunately though they‘re not very complex). Alternatively you might be able to change the URL slightly whenever you want to fetch a new image (i.e. adding a param like „&dummyId=<uuid>„). In this case be aware that the shipped disk cache will not delete images on it’s own, so the directory can grow quite fast if you have lots of different images. A third way would be to remove the caching altogether by setting nil as the caches. 

Hope this helps!

**Comment by anudeep94** [comment]
Similar to Picasso in android, is there Network policies and Memory Policies in Matisse?

**Comment by frenetisch-applaudierend** [comment]
No there is no such thing. Alas this is a very simple library, if you need to have more advanced concepts you have the possibility to provide custom image loaders and caches. But you need to implement the functionality yourself, I‘m afraid
